package org.firstinspires.ftc.teamcode;

public class ToDos {
    // TODO: REMOVE COLOR SENSOR IN DRIVER HUB CONFIG AND CODE IN ALL CLASSES EXECPT SORTER TEST (DONT REMOVE IF IT WORKS OR IF YOURE NNOT TESITNG THAT CLASS)
}
